/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-container": "#956d2b",
        "on-tertiary-fixed-variant": "#783119",
        "on-secondary-fixed": "#1f1b18",
        "surface-variant": "#e4e2de",
        "tertiary-fixed": "#ffdbd0",
        "on-tertiary-fixed": "#390b00",
        "on-tertiary": "#ffffff",
        "surface-container": "#efeeea",
        "on-primary-fixed": "#281800",
        "surface-tint": "#7c5716",
        "outline-variant": "#d3c4b3",
        "inverse-primary": "#f0be73",
        "on-secondary-fixed-variant": "#4b4642",
        "error": "#ba1a1a",
        "tertiary-container": "#b15d41",
        "secondary-fixed-dim": "#cdc5c0",
        "on-surface": "#1b1c1a",
        "inverse-surface": "#30312e",
        "background": "#fbf9f5",
        "on-secondary": "#ffffff",
        "primary-fixed": "#ffddaf",
        "inverse-on-surface": "#f2f0ed",
        "secondary-container": "#eae1db",
        "surface": "#fbf9f5",
        "surface-dim": "#dbdad6",
        "on-surface-variant": "#4f4539",
        "surface-container-highest": "#e4e2de",
        "on-error-container": "#93000a",
        "secondary-fixed": "#eae1db",
        "on-background": "#1b1c1a",
        "on-primary": "#ffffff",
        "outline": "#817567",
        "error-container": "#ffdad6",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-container": "#fffbff",
        "on-primary-fixed-variant": "#614000",
        "tertiary-fixed-dim": "#ffb59d",
        "on-primary-container": "#fffbff",
        "surface-container-high": "#eae8e4",
        "secondary": "#635d59",
        "primary-fixed-dim": "#f0be73",
        "on-error": "#ffffff",
        "surface-bright": "#fbf9f5",
        "surface-container-low": "#f5f3ef",
        "primary": "#7a5513",
        "tertiary": "#93452b",
        "on-secondary-container": "#69635f"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "space-md": "1rem",
        "margin-desktop": "3rem",
        "margin-mobile": "1.25rem",
        "gutter-desktop": "2rem",
        "space-xl": "2.5rem",
        "gutter": "1.5rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-lg": "1.5rem",
        "margin": "1.5rem",
        "gutter-mobile": "1rem"
      },
      fontFamily: {
        "label-sm": [ "Inter", "sans-serif" ],
        "headline-sm": [ "EB Garamond", "serif" ],
        "headline-md": [ "EB Garamond", "serif" ],
        "body-sm": [ "Inter", "sans-serif" ],
        "headline-lg-mobile": [ "EB Garamond", "serif" ],
        "label-md": [ "Inter", "sans-serif" ],
        "display": [ "EB Garamond", "serif" ],
        "body-lg": [ "Inter", "sans-serif" ],
        "title-md": [ "Inter", "sans-serif" ],
        "display-mobile": [ "EB Garamond", "serif" ],
        "headline-lg": [ "EB Garamond", "serif" ],
        "body-md": [ "Inter", "sans-serif" ],
        "serif": [ "EB Garamond", "serif" ],
        "sans": [ "Inter", "sans-serif" ]
      },
      fontSize: {
        "label-sm": [ "0.6875rem", { "lineHeight": "1.3", "letterSpacing": "0.08em", "fontWeight": "500" } ],
        "headline-sm": [ "1.25rem", { "lineHeight": "1.4", "letterSpacing": "0em", "fontWeight": "500" } ],
        "headline-md": [ "1.75rem", { "lineHeight": "1.3", "letterSpacing": "0em", "fontWeight": "400" } ],
        "body-sm": [ "0.8125rem", { "lineHeight": "1.5", "letterSpacing": "0.01em", "fontWeight": "400" } ],
        "headline-lg-mobile": [ "1.75rem", { "lineHeight": "1.25", "letterSpacing": "0em", "fontWeight": "400" } ],
        "label-md": [ "0.75rem", { "lineHeight": "1.3", "letterSpacing": "0.12em", "fontWeight": "600" } ],
        "display": [ "3.5rem", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "400" } ],
        "body-lg": [ "1.125rem", { "lineHeight": "1.6", "letterSpacing": "0em", "fontWeight": "400" } ],
        "title-md": [ "1rem", { "lineHeight": "1.5", "letterSpacing": "0.01em", "fontWeight": "600" } ],
        "display-mobile": [ "2.25rem", { "lineHeight": "1.15", "letterSpacing": "-0.01em", "fontWeight": "400" } ],
        "headline-lg": [ "2.5rem", { "lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "400" } ],
        "body-md": [ "0.9375rem", { "lineHeight": "1.6", "letterSpacing": "0em", "fontWeight": "400" } ]
      }
    }
  },
  plugins: [],
}
